title: Jacob Huang

baseurl: /all-in-one
theme: minima

show_excerpts: true

minima:
  skin: dark
  social_links:
    github: JacobHuang91
    youtube: channel/UCF8C7SraW-e1Ht3JakcNqGQ
  date_format: "%Y-%m-%d"

plugins:
  - jekyll-feed

collections:
  leetcode:
    output: true
  ood:
    output: true
  system_design:
    output: true

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - code
  - templates
  - books
  - interview
