title: Jacob Huang
description: https://github.com/JacobHuang91/all-in-one
author: "Jacob Huang"
baseurl: /all-in-one
theme: minima

show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

plugins:
  - jekyll-feed

collections:
  leetcode:
    output: true

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - code
  - templates
