title: Jacob Huang
description: Happy coding!
author:
  name: Jacob Huang

baseurl: /all-in-one
theme: minima

show_excerpts: true

minima:
  date_format: "%Y-%m-%d"
  skin: dark
  social_links:
    github: https://github.com/JacobHuang91
    youtube: https://www.youtube.com/channel/UCF8C7SraW-e1Ht3JakcNqGQ

plugins:
  - jekyll-feed

collections:
  leetcode:
    output: true

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - code
  - templates
